### ISSUE TITLE
isinstance seems to be too strict

### ISSUE THREAD

**Issue by ferrine** [wd60622/conjugate#1]
Shouldn't this just check for numeric types? How does it check against pytensor? Is it supposed to with with pytensor?
https://github.com/wd60622/conjugate/blob/18e777335f228aeb565c41a405b0aad803eb510a/conjugate/distributions.py#L110

**Comment by wd60622** [comment]
Seems like a good suggestion

I can make the change. I just learned about `runtime_checkable` with Protocol so it would work with that 
https://stackoverflow.com/questions/59461689/how-can-you-test-that-a-python-typing-protocol-is-a-subclass-of-another-protocol

**Comment by ferrine** [comment]
What is the issue to rely on dynamic typing system and remove the check at all?

**Comment by wd60622** [comment]
> What is the issue to rely on dynamic typing system and remove the check at all?

Totally, fair enough. Can go with that

**Comment by wd60622** [comment]
The isinstance is removed
